name: .NET Tests

on:
  push:
    branches: [ main, lab_1 ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore ./RealtorAgency/RealtorAgency.sln

      - name: Build
        run: dotnet build ./RealtorAgency/RealtorAgency.sln --no-restore --configuration Release

      - name: Test
        run: dotnet test ./RealtorAgency/Tests/Tests.csproj --configuration Release --verbosity normal